apiVersion: v1
kind: Service
metadata:
  name: hermes
  labels:
    app.kubernetes.io/name: hermes
    app.kubernetes.io/part-of: heliantheon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hermes
  ports:
    - name: http
      port: 18000
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc

